# Generated by Django 4.1.7 on 2023-08-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireman', '0012_societate_banca_societate_cont_alter_contract_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societate',
            name='banca',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='societate',
            name='cont',
            field=models.IntegerField(default=' '),
        ),
    ]
