# Generated by Django 4.1.7 on 2023-08-01 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireman', '0018_remove_contract_client_id_remove_contract_societate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cost',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='garantie_produs',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 8, 1, 7, 25, 48, 313826, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
