# Generated by Django 4.1.7 on 2023-06-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireman', '0008_categorie_poza_alter_contract_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buton_meniu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buton', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Buton',
                'verbose_name_plural': 'Butoane',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
