# Generated by Django 4.1.7 on 2023-06-30 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireman', '0010_alter_categorie_poza_alter_contract_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='data',
            field=models.DateField(default=datetime.date(2023, 7, 1)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='data_start',
            field=models.DateField(default=datetime.date(2023, 7, 1)),
        ),
        migrations.AlterField(
            model_name='produs',
            name='poza',
            field=models.ImageField(null=True, upload_to='hireman/static/media/'),
        ),
        migrations.AlterField(
            model_name='reparatie',
            name='data_end',
            field=models.DateField(default=datetime.date(2023, 7, 1)),
        ),
        migrations.AlterField(
            model_name='reparatie',
            name='data_start',
            field=models.DateField(default=datetime.date(2023, 7, 1)),
        ),
    ]
