# Generated by Django 4.1.7 on 2023-08-01 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hireman', '0013_alter_societate_banca_alter_societate_cont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societate',
            name='banca',
        ),
        migrations.RemoveField(
            model_name='societate',
            name='cont',
        ),
    ]
