# Generated by Django 4.1.7 on 2023-08-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireman', '0015_societate_banca_societate_cont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societate',
            name='cont',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
