# Generated by Django 4.1.7 on 2023-08-01 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireman', '0016_alter_societate_cont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='nr',
        ),
        migrations.AddField(
            model_name='contract',
            name='adresa_client',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='adresa_livrare',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='adresa_srl',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='banca_client',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='banca_srl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='cnp',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='cont_client',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='cont_srl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='cui',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='director',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='mail_client',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='mail_srl',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='nr_contract',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='nr_zile',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='nume_client',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='nume_srl',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='produs',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='tel_client',
            field=models.BigIntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='tel_srl',
            field=models.BigIntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 8, 1, 7, 19, 18, 912432, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='data_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='societate',
            name='cont',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
