# Generated by Django 4.1.7 on 2023-08-01 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireman', '0017_remove_contract_nr_contract_adresa_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='societate',
        ),
        migrations.AlterField(
            model_name='contract',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 8, 1, 7, 23, 16, 530802, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
