# Generated by Django 4.1.7 on 2023-05-10 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireman', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'managed': True, 'verbose_name': 'Contract', 'verbose_name_plural': 'Contracte'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='cos',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='perioada',
        ),
        migrations.AlterField(
            model_name='contract',
            name='data',
            field=models.DateField(default=datetime.date(2023, 5, 10)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='data_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 14, 52, 49, 851220)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='data_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 14, 52, 49, 851220)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='observatii',
            field=models.CharField(default='fara observatii', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reparatie',
            name='data_end',
            field=models.DateField(verbose_name=datetime.datetime(2023, 5, 10, 14, 52, 49, 851220)),
        ),
        migrations.AlterField(
            model_name='reparatie',
            name='data_start',
            field=models.DateField(verbose_name=datetime.datetime(2023, 5, 10, 14, 52, 49, 851220)),
        ),
        migrations.AlterModelTable(
            name='contract',
            table='',
        ),
    ]
