# Generated by Django 4.1.7 on 2023-05-10 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireman', '0002_alter_contract_options_remove_client_cos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='data_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='data_start',
            field=models.DateField(default=datetime.date(2023, 5, 10)),
        ),
        migrations.AlterField(
            model_name='reparatie',
            name='data_end',
            field=models.DateField(verbose_name=datetime.datetime(2023, 5, 10, 14, 59, 12, 230307)),
        ),
        migrations.AlterField(
            model_name='reparatie',
            name='data_start',
            field=models.DateField(verbose_name=datetime.datetime(2023, 5, 10, 14, 59, 12, 230307)),
        ),
    ]
