# Generated by Django 4.1.7 on 2023-06-05 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireman', '0004_meniubar_alter_contract_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meniubar',
            options={'managed': True, 'verbose_name': 'meniu', 'verbose_name_plural': 'meniuri'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='data',
            field=models.DateField(default=datetime.date(2023, 6, 5)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='data_start',
            field=models.DateField(default=datetime.date(2023, 6, 5)),
        ),
        migrations.AlterField(
            model_name='reparatie',
            name='data_end',
            field=models.DateField(default=datetime.date(2023, 6, 5)),
        ),
        migrations.AlterField(
            model_name='reparatie',
            name='data_start',
            field=models.DateField(default=datetime.date(2023, 6, 5)),
        ),
        migrations.AlterModelTable(
            name='meniubar',
            table='',
        ),
    ]
