# Generated by Django 4.1.7 on 2023-06-07 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireman', '0005_alter_meniubar_options_alter_contract_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeniuBar',
        ),
        migrations.AlterField(
            model_name='contract',
            name='data',
            field=models.DateField(default=datetime.date(2023, 6, 7)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='data_start',
            field=models.DateField(default=datetime.date(2023, 6, 7)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reparatie',
            name='data_end',
            field=models.DateField(default=datetime.date(2023, 6, 7)),
        ),
        migrations.AlterField(
            model_name='reparatie',
            name='data_start',
            field=models.DateField(default=datetime.date(2023, 6, 7)),
        ),
    ]
