# Generated by Django 4.1.7 on 2023-08-01 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireman', '0011_alter_contract_data_alter_contract_data_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='societate',
            name='banca',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='societate',
            name='cont',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='contract',
            name='data',
            field=models.DateField(default=datetime.date(2023, 8, 1)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='data_start',
            field=models.DateField(default=datetime.date(2023, 8, 1)),
        ),
        migrations.AlterField(
            model_name='reparatie',
            name='data_end',
            field=models.DateField(default=datetime.date(2023, 8, 1)),
        ),
        migrations.AlterField(
            model_name='reparatie',
            name='data_start',
            field=models.DateField(default=datetime.date(2023, 8, 1)),
        ),
    ]
