# Generated by Django 4.1.7 on 2023-08-04 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireman', '0022_remove_contract_nr_contract_remove_contract_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 8, 4, 14, 59, 48, 259800, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pdf_path',
            field=models.FileField(default='hireman/static/contracte_pdf/contract-nr1-din:<built-in method date of datetime.datetime object at 0x000001C1A07667F0>', null=True, upload_to='hireman/static/contracte_pdf/'),
        ),
        migrations.AlterField(
            model_name='reparatie',
            name='data_end',
            field=models.DateField(default=datetime.datetime(2023, 8, 4, 14, 59, 48, 259800, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reparatie',
            name='data_start',
            field=models.DateField(default=datetime.datetime(2023, 8, 4, 14, 59, 48, 259800, tzinfo=datetime.timezone.utc)),
        ),
    ]
