# Generated by Django 4.2.5 on 2023-09-20 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireman', '0023_alter_contract_data_alter_contract_pdf_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='adresa_livrare',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 9, 20, 23, 7, 35, 280067, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pdf_path',
            field=models.FileField(default='hireman/static/contracte_pdf/contract-nr1-din:2023-09-20 23:07:35.280067+00:00', null=True, upload_to='hireman/static/contracte_pdf/'),
        ),
        migrations.AlterField(
            model_name='reparatie',
            name='data_end',
            field=models.DateField(default=datetime.datetime(2023, 9, 20, 23, 7, 35, 277067, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reparatie',
            name='data_start',
            field=models.DateField(default=datetime.datetime(2023, 9, 20, 23, 7, 35, 277067, tzinfo=datetime.timezone.utc)),
        ),
    ]
